### ISSUE TITLE
tutorial doesn't work on 3.8

### ISSUE THREAD

**Issue by t4n1o** [meeshkan/hmt#218]
It seems hmt tutorial doesn't work on 3.8 as advertised in your readme.

### Steps to Reproduce
Linux
Python 3.8
install hmt via `python3 -m pip hmt`
run tutorial

### Actual Result 

```
Traceback (most recent call last):
  File "__hmt__/api_calls.py", line 1, in <module>
    from urllib import request
ImportError: cannot import name request

```
